/* Source-backed application explorer; no material-demand or grade-fit inference. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const query=new URLSearchParams(location.search);
  let data,sectorId=query.get('sector')||'',recordId=query.get('plant')||'';
  let handoffNote='',suppressAutoSelection=false;
  const ids=record=>record.source_ids||record.sources||[];
  const sector=()=>data.sectors.find(s=>s.id===sectorId);
  const allPlants=()=>data.plants||[];
  const plant=id=>allPlants().find(p=>p.id===id);
  const manufacturer=id=>(data.manufacturers||[]).find(m=>m.id===id);
  const text=value=>typeof value==='string'?value:value?.statement||value?.summary||value?.description||value?.label||'';
  function sources(sourceIds){const records=[...new Set(sourceIds||[])].map(id=>data.sources.find(s=>s.id===id)).filter(Boolean);return records.length?`<details class="ap-evidence-links"><summary>Read ${records.length} primary source${records.length===1?'':'s'}</summary>${records.map(s=>`<a href="${/^https:\/\//.test(s.url)?esc(s.url):'#'}" target="_blank" rel="noopener">${esc(s.title)} ↗<small>${esc(s.date||s.publication_date||'Source date not assigned')}${s.locator?' · '+esc(s.locator):''}</small></a>`).join('')}</details>`:'';}
  function plantsForSector(){const s=sector();return allPlants().filter(p=>(p.sector_ids||[]).includes(s.id)||(s.plant_ids||[]).includes(p.id));}
  function manufacturersForSector(){const s=sector(),plants=plantsForSector(),ids=new Set([...(s.manufacturer_ids||[]),...plants.map(p=>p.manufacturer_id).filter(Boolean)]);return (data.manufacturers||[]).filter(m=>ids.has(m.id)||(m.sector_ids||[]).includes(s.id));}
  function routesForSector(){const s=sector();return (data.routes||[]).filter(r=>(r.sector_ids||[]).includes(s.id)||(s.route_ids||[]).includes(r.id));}
  function mapLink(p=null){const q=new URLSearchParams({layer:'applications',sector:sectorId});if(p)q.set('plant',p.id);return `grades.html?${q}#origins`;}
  function machineKind(s){if(s.id==='medical_permanent')return 'medical';if(s.id==='datacenter_equipment')return 'cooling';if(s.id==='electronics')return 'electronics';if(s.id==='hvac_appliances')return 'compressor';if(s.id==='defense_aerospace')return 'aerospace';if(s.id==='industrial_motors')return 'motor';const value=`${s.id} ${s.label}`.toLowerCase();return /wind/.test(value)?'wind':/robot|automat|industrial/.test(value)?'robot':/ev|vehicle|traction/.test(value)?'ev':'motor';}
  const motor=`<ellipse cx="296" cy="114" rx="43" ry="54" fill="#18271d"/><path d="M209 60h87v108h-87"/><ellipse cx="209" cy="114" rx="43" ry="54"/><ellipse cx="209" cy="114" rx="31" ry="41" fill="#101916"/><ellipse cx="209" cy="114" rx="22" ry="30" fill="#8aab95"/><path d="M199 87h20v11h-20zM199 131h20v11h-20z" fill="#c5a46b"/><path d="M209 107h143v14H209z"/><path d="M194 170v17h119v-17M176 63l37-13h81l35 17M168 99h-15v32h15"/>`;
  const drawings={
    ev:`<path d="M48 145v-29l33-14 32-39h132l65 43 58 16v34H48Z"/><path d="m121 72-25 32h190l-43-32ZM160 74v30M224 74v30" fill="#101916"/><circle cx="111" cy="149" r="26" fill="#101916"/><circle cx="111" cy="149" r="15"/><circle cx="304" cy="149" r="26" fill="#101916"/><circle cx="304" cy="149" r="15"/><path d="M58 127h24m260-1h19M141 145h116M144 114h95v22h-95Z" fill="#263c2e"/><path d="M155 119v12m13-12v12m13-12v12m13-12v12m13-12v12m13-12v12" stroke="#8aab95"/><path d="M253 117h28v22h-28Z" fill="#c5a46b"/><path d="m273 117 3-18 18-10"/><circle cx="352" cy="49" r="37" fill="#101916"/><circle cx="352" cy="49" r="27"/><circle cx="352" cy="49" r="22" fill="#8aab95"/><path d="M342 30h20v8h-20zM342 60h20v8h-20z" fill="#c5a46b"/><path d="M352 41h33v15h-33Z" fill="#253a2c"/><path d="M287 101 328 78" stroke-dasharray="4 5"/><path d="M41 186h348" stroke="#8aab9540"/>`,
    robot:`<path d="M100 191h118l-11-26h-96Z"/><path d="M127 164V99l38-9 8 75"/><ellipse cx="148" cy="111" rx="27" ry="30"/><ellipse cx="148" cy="111" rx="15" ry="18" fill="#c5a46b"/><path d="m167 91 53-51 30 21-60 57"/><circle cx="235" cy="50" r="23"/><circle cx="235" cy="50" r="12" fill="#c5a46b"/><path d="m250 41 73 23-6 25-70-21"/><ellipse cx="319" cy="74" rx="19" ry="23"/><ellipse cx="319" cy="74" rx="10" ry="13" fill="#c5a46b"/><path d="m331 79 21 24-12 9-24-18m34 6 21 8v22m-26-12-14 11v18"/><path d="M47 190h49m129 0h135m-36-42h50v43h-50zM341 158v22m14-22v22" stroke="#8aab95"/><path d="M99 195h283" stroke="#8aab9540"/>`,
    wind:`<path d="M200 97h38v21h-38zM211 117l-7 87h26l-6-87"/><ellipse cx="200" cy="107" rx="14" ry="16"/><path d="m201 94 13-66 13-11-12 77ZM187 111l-62-27-15-13 77 28ZM203 120l35 54 1 17-47-65Z"/><path d="M180 205h69M53 205h336" stroke="#8aab9550"/><path d="M254 78h106v73H254Z" fill="#101916"/><path d="M264 87h28v55h-28zM310 87h30v55h-30z" fill="#263b2c"/><path d="M269 94h17v42h-17zM316 94h17v42h-17z" fill="#bb785d"/><circle cx="302" cy="114" r="20" fill="#8aab95"/><path d="M294 96h16v7h-16zM294 126h16v7h-16z" fill="#c5a46b"/><path d="M292 110h77v9h-77z" fill="#263b2c"/><path d="m237 111 17 3" stroke-dasharray="4 5"/>`,
    compressor:`<ellipse cx="198" cy="73" rx="63" ry="30"/><path d="M135 73v77c0 37 126 37 126 0V73"/><ellipse cx="198" cy="151" rx="63" ry="29" fill="none"/><path d="M151 172v23h94v-23M127 194h126M172 77V41h-30V23h-50M245 88h50V46h50M262 145h55v33h39"/><path d="M159 97h78v45h-78z" fill="#18271d" stroke-dasharray="4 5"/><circle cx="199" cy="120" r="16" fill="#8aab95"/><path d="M199 106v29m-10-20h20m-20 10h20"/><path d="M52 199h322" stroke="#8aab9540"/>`,
    aerospace:`<path d="M44 73h192l41 8-19 17H71l-27-12Z"/><path d="m118 76 69-36h19l-42 38m-48 17 50 30h22l-28-32m62-20 29-28h14l-11 31M252 86l42-2"/><path d="M144 150h147v32H144zM125 156h19v20h-19zM291 159h54v14h-54zM165 141v9m13-9v9m75-9v9m13-9v9"/><circle cx="121" cy="166" r="10" fill="#8aab95"/><circle cx="350" cy="166" r="8"/><path d="M202 150v32m-20-32v32m40-32v32M123 194h237m-143-77 8 23" stroke="#8aab95" stroke-dasharray="4 4"/>`,
    medical:`<path d="M197 35h86v145h-86Z"/><ellipse cx="196" cy="107" rx="63" ry="73"/><ellipse cx="196" cy="107" rx="38" ry="49" fill="#101916"/><ellipse cx="203" cy="107" rx="25" ry="34" fill="#263b2c"/><path d="M51 124h157v16H51zM74 141v47h104v-47M62 188h129M304 71h53v88h-53zM313 82h35v41h-35zM317 160v28M299 188h48"/><path d="M154 63c15-22 28-26 38-25m-40 95c12 25 25 32 40 34" stroke="#8aab95"/>`,
    cooling:`<path d="M214 53h132v128H214zM226 64h108v70H226z"/><path d="M237 66v66m14-66v66m14-66v66m14-66v66m14-66v66m14-66v66m14-66v66" stroke="#8aab95"/><path d="M240 181v15h71v-15M77 139h79v37H77zM88 176v20h57v-20M99 140v-33h81V83h34M145 144v-32h42v49h27"/><circle cx="99" cy="156" r="17" fill="#18271d"/><circle cx="99" cy="156" r="8" fill="#8aab95"/><path d="M154 148h24v16h-24M50 198h320"/>`,
    electronics:`<path d="M79 42h181v154H79zM93 57h152v123H93z"/><circle cx="171" cy="118" r="50" fill="#101916"/><circle cx="171" cy="118" r="15"/><path d="m104 74 33 42 43 9-9 9-48-9-30-37Z" fill="#8aab95"/><path d="M88 65h31v20H88z" fill="#c5a46b"/><path d="M292 65h43l23-15v105l-23-15h-43z"/><path d="M304 80h21v47h-21z" fill="#c5a46b"/><path d="M292 91h-12v24h12M53 204h311"/>`,
    motor:`${motor}<path d="M45 88h57v76H45zM102 112h48v11h-48zM52 169v14h61v-14M58 94v62m12-62v62m12-62v62" stroke="#8aab95"/><path d="M49 191h319" stroke="#8aab9540"/>`
  };
  function render(){
    const s=sector(),requirements=s.requirements||[],alternatives=s.alternatives||[],dimensions=s.criticality||{},companies=manufacturersForSector(),plants=plantsForSector(),routes=routesForSector();
    $('application-picker').innerHTML=data.sectors.map((item,i)=>`<button type="button" data-sector="${esc(item.id)}" aria-pressed="${item.id===s.id}"><span>0${i+1} / APPLICATION</span>${esc(item.label)}</button>`).join('');
    $('application-status').textContent=`${s.label} · ${plants.length} named place records · ${routes.length} source relationship${routes.length===1?'':'s'} · evidence as of ${data.as_of||data.metadata?.as_of||'the cited dates'}${data.preliminary?' · priority snapshot; broader review pending':''}${handoffNote?' · '+handoffNote:''}`;
    $('application-story').innerHTML=`<div class="ap-machine"><p class="micro-label">${s.model_compatibility==='chemistry_unspecified'?'MACHINE ARCHITECTURE · MATERIAL NOT ASSIGNED':'SELECTED CONFIGURATION · ILLUSTRATIVE'}</p><svg viewBox="0 0 420 220" role="img" aria-label="${esc(s.label)}: illustrative machinery, material requirements depend on source and design">${drawings[machineKind(s)]}</svg><p class="ap-machine-caption">Physical configuration illustration · no quantified demand, supplier assignment or grade suitability inferred.</p></div><div class="ap-story-copy"><p class="eyebrow">${esc(s.label)}</p><h2>${esc(s.headline||s.label)}</h2><p>${esc(s.description||'')}</p><p class="ap-boundary">${esc(text(s.technology_boundary)||'Magnet requirements depend on the actual machine design. This sector label does not establish universal rare-earth use.')}</p>${s.model_boundary?`<p class="ap-boundary">${esc(s.model_boundary)}</p>`:''}${sources(ids(s))}${['robot_automation','industrial_motors'].includes(s.id)?'<a class="ap-industry-link" href="#industry-insights">Practitioner context: buyer roles, sourcing & qualification questions ↗</a>':''}</div>`;
    $('application-requirements').innerHTML=requirements.map(r=>`<article class="ap-requirement"><span class="ap-material-symbol">${esc(r.symbol||r.material||(String(r.material_or_product||'').length<=15?r.material_or_product:'◇'))}</span><h3>${esc(r.label||r.material_or_product||r.product||'Product requirement')}</h3><p>${esc(r.role||r.statement||'')}</p>${r.basis?`<p>${esc(r.basis)}</p>`:''}${sources(ids(r))}</article>`).join('')||'<p class="ap-empty">No source-specific material requirement is assigned. A generic sector name cannot supply a bill of materials.</p>';
    $('application-alternatives').innerHTML=`<h3>Another design may use another material.</h3><div class="ap-alternative-grid">${alternatives.map(a=>`<article><h4>${esc(a.label)}</h4><p>${esc(a.tradeoff||a.statement||a.description||'')}</p>${sources(ids(a))}</article>`).join('')||'<p>No substitute is quantified in the saved source package. Do not infer interchangeability.</p>'}</div>`;
    $('application-criticality').innerHTML=[['material_dependence','01','Material dependence'],['substitution_redesign','02','Substitution / redesign'],['qualification_switching','03','Qualification / switching'],['interruption_consequence','04','Interruption consequences'],['supply_exposure','05','Supply exposure'],['demand_pressure','06','Demand pressure']].map(([key,no,label])=>`<article><span class="ap-dimension-mark">${no}</span><h3>${label}</h3>${dimensions[key]?.label?`<span class="ap-judgment-label">${esc(String(dimensions[key].label).replaceAll('_',' '))} · analyst judgment</span>`:''}<p>${esc(text(dimensions[key])||'The reviewed sources do not quantify this dimension for the selected application.')}</p>${dimensions[key]?.basis?`<p class="ap-dimension-basis">${esc(dimensions[key].basis)}</p>`:''}${sources(ids(dimensions[key]||{}))}</article>`).join('');
    const grouped=companies.map(m=>({m,plants:plants.filter(p=>p.manufacturer_id===m.id||(m.plant_ids||[]).includes(p.id))}));const groupedIds=new Set(grouped.flatMap(g=>g.plants.map(p=>p.id)));for(const p of plants.filter(p=>!groupedIds.has(p.id)))grouped.push({m:{id:p.operator||p.id,name:p.operator||p.name,role:'Place record; corporate capability and customer route require separate evidence'},plants:[p]});
    $('application-network').innerHTML=grouped.map(({m,plants:ps})=>`<article class="ap-company"><button type="button" data-record="${esc(m.id)}"><h3>${esc(m.name)}</h3></button><p>${esc(m.role||'Product/manufacturer record; see sources')}</p><div class="ap-plant-list">${ps.map(p=>`<button type="button" data-record="${esc(p.id)}" class="${recordId===p.id?'selected':''}">${esc(p.name)}<small>${esc(p.place||p.city||p.region||'')} · ${esc(p.country||'Location unassigned')}<br>${esc(p.plant_type||'Named site')} · ${esc(p.status_label||p.status||'See source status')}</small></button>`).join('')||'<p>No operating factory location is established in this saved record. Headquarters are not substituted for plants.</p>'}</div></article>`).join('')||'<p>No named manufacturer or operating plant is established in this sector package.</p>';
    $('application-routes').innerHTML=routes.map(routeHTML).join('')||'<p class="ap-empty">No named supplier-to-application route is established by the reviewed evidence. Manufacturer capability is not a supplier contract.</p>';
    updateLabLink();
    if(!suppressAutoSelection&&!plants.some(p=>p.id===recordId)&&!companies.some(m=>m.id===recordId))recordId=plants[0]?.id||companies[0]?.id||'';
    if(recordId)showRecord(recordId);else $('application-record').innerHTML=handoffNote?`<p class="ap-empty">${esc(handoffNote)} Choose a documented site from the list.</p>`:'';
    $('application-scope').innerHTML=`<p>${esc(data.scope||data.metadata?.scope||'Selected sourced application records, not a complete factory or consumption census.')}</p>${(data.caveats||data.boundaries||[]).map(c=>`<p>${esc(c)}</p>`).join('')}<p>Plant locations, product capability, ownership, named customer contracts, deliveries and volume are different facts. Named but anonymous customer programs do not identify a carmaker or robot OEM. No automatic connection from a magnet grade example to a sector bill of materials is made.</p><p>Material dependence, substitution/redesign, qualification/switching, interruption consequences, supply exposure and demand pressure are separate analyst judgments. Their scope and uncertainty depend on the cited product and architecture; no universal sector ranking or combined score is computed. The linked scenario laboratory retains illustrative, editable demand and acceptance assumptions.</p><p><a href="data/application-supply.json">Download the application evidence JSON</a> · <a href="${mapLink()}">Open this sector’s map layer</a></p>`;
  }
  function routeHTML(r){const steps=r.steps||[r.source,r.target||(r.to?{label:r.to,gap:true}:null)].filter(Boolean);return `<article class="ap-route"><div><h3>${esc(r.title||r.label||r.product||'Source relationship')}</h3><span class="ap-route-status">${esc(r.status_label||r.status||r.evidence_class||'See evidence')}</span></div><div class="ap-route-steps">${steps.map((step,i)=>{const id=typeof step==='string'?step:step.id||step.node_id,record=plant(id)||manufacturer(id);return `${i?'<span class="ap-step-arrow" aria-hidden="true">→</span>':''}${record?`<button type="button" data-record="${esc(id)}">${esc(record.name)}</button>`:`<span class="${typeof step==='object'&&step.gap?'ap-gap':''}">${esc(typeof step==='string'?step:step.label||step.name||id||'Undisclosed step')}</span>`}`;}).join('')}</div><p>${esc(r.summary||r.description||'')}</p>${r.product?`<p>Product: ${esc(r.product)}</p>`:''}<p>Relationship type: ${esc((r.evidence_type||r.evidence_class||'see source').replaceAll('_',' '))}. Company-level endpoints do not identify receiving plants.</p>${[...(r.gaps||[]),...(r.caveats||[])].map(g=>`<p class="ap-route-caveat">${esc(text(g))}</p>`).join('')}${r.physical_flow===false?'<p class="ap-route-caveat">This is a capability, contract or relationship record; it does not establish continuing delivered volume or a complete physical chain.</p>':''}${sources(ids(r))}${r.map_path_id?`<p><a class="ap-map-link" href="grades.html?path=${encodeURIComponent(r.map_path_id)}#origins">Inspect the original evidence path ↗</a></p>`:''}</article>`;}
  function showRecord(id){recordId=id;const p=plant(id),m=manufacturer(id);if(!p&&!m)return;updateLabLink();if(p){const parent=manufacturer(p.manufacturer_id);$('application-record').innerHTML=`<div><p class="eyebrow">${esc(p.plant_type||'Named place')} · ${esc(p.country||'Location unassigned')}</p><h3>${esc(p.name)}</h3><p class="ap-record-status">${esc(p.status_label||p.status||'See cited status')}</p><p>${esc(p.product||p.products?.join(' / ')||'Product not assigned')}</p><p>${esc(p.place||p.city||p.region||'')}<br>${esc(p.operator||parent?.name||'Operator not assigned')}</p>${p.architecture_context?`<p class="ap-boundary">${esc(text(p.architecture_context))}</p>`:''}${p.model_boundary?`<p class="ap-boundary">${esc(p.model_boundary)}</p>`:''}<p>${esc(p.location_note||p.location_precision||'Location precision not assigned; no surveyed factory coordinate is inferred.')}</p><a class="ap-map-link" href="${mapLink(p)}">Inspect this original application map pin ↗</a></div><div><p class="eyebrow">What the evidence does—and does not—establish</p><p>${esc(p.summary||p.description||'A product or facility disclosure does not identify a magnet supplier, accepted specimen or delivered allocation.')}</p>${(p.caveats||[]).map(c=>`<p>${esc(c)}</p>`).join('')}${sources(ids(p))}<p>Source record: ${esc(p.id)}. Scenario capacities, recipe suitability and demand remain separately assumed.</p></div>`;}else{$('application-record').innerHTML=`<div><p class="eyebrow">Manufacturer / company record</p><h3>${esc(m.name)}</h3><p>${esc(m.role||m.description||'')}</p><p>${esc(m.summary||'Company product capability is distinct from named factory output or magnet supplier provenance.')}</p></div><div>${sources(ids(m))}<p>${esc((m.caveats||[]).join(' '))}</p><p>A headquarters address is not evidence of production at that location.</p></div>`;}
    document.querySelectorAll('.ap-plant-list [data-record]').forEach(b=>b.classList.toggle('selected',b.dataset.record===id));
  }
  function updateLabLink(){const s=sector(),p=plant(recordId),ndfeb=s.model_compatibility==='ndfeb_context'&&(!p?.model_compatibility||p.model_compatibility==='ndfeb_context')&&!/smco|samarium.?cobalt/i.test(`${p?.product||''} ${p?.plant_type||''}`),q=new URLSearchParams({sector:s.id});if(p)q.set('application_plant',p.id);$('application-open-lab').href=`chain.html?${q}#chain-experiment`;$('application-open-lab').innerHTML=`${ndfeb?'Test separate assumed NdFeB demand':'Explore a separate generic NdFeB example'} <span aria-hidden="true">↗</span><small>${ndfeb?'Editable demand, inventories & acceptance timing':'This does not model the selected material or machine'}</small>`;$('application-experiment-note').textContent=(p?.model_boundary?p.model_boundary+' ':s.model_boundary?s.model_boundary+' ':'')+(s.scenario?.acceptance_note||'Sector selection is context, not a calibrated bill of materials or a claim that either specimen is suitable for this machine.')+(p?` Selected place: ${p.name}. This source record is retained as context, not assigned as the simulated customer.`:'');}
  async function init(){try{const response=await fetch('data/application-supply.json');if(!response.ok)throw new Error('Application evidence request failed');data=await response.json();if(!data.sectors?.length)throw new Error('No reviewed sector records');const requested=plant(recordId)||manufacturer(recordId);if(recordId){if(requested){const eligible=data.sectors.filter(s=>(requested.sector_ids||[]).includes(s.id)||(s.plant_ids||[]).includes(recordId));if(eligible.length&&!eligible.some(s=>s.id===sectorId)){if(query.has('sector'))handoffNote='The requested sector does not match this record; showing its documented '+eligible[0].label+' context.';sectorId=eligible[0].id;}else if(!eligible.length){handoffNote='This record has no established application-sector assignment.';recordId='';suppressAutoSelection=true;}}else{handoffNote='The requested site identifier is not in this evidence set.';recordId='';suppressAutoSelection=true;}}if(!data.sectors.some(s=>s.id===sectorId))sectorId=data.sectors[0].id;render();$('application-picker').onclick=e=>{const b=e.target.closest('[data-sector]');if(b){sectorId=b.dataset.sector;recordId='';handoffNote='';suppressAutoSelection=false;render();history.replaceState(null,'',`applications.html?sector=${encodeURIComponent(sectorId)}`);}};document.addEventListener('click',e=>{const b=e.target.closest('[data-record]');if(b)showRecord(b.dataset.record);});}catch(e){$('application-status').textContent=`Application evidence could not load: ${e.message}. No supplier relationships or requirements have been invented.`;}}
  init();
})();
