/* Presentation and evidence navigation only. All physical accounting is performed
   by rareearth.chain in the shared Python worker. No JavaScript simulation. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'—';
  const policyNames={'none':'No new intervention','upstream-diversification':'Mining diversity','processing':'Independent processing','magnets-qualification':'Magnets & acceptance','finished-inventory':'Qualified stocks','mix':'Mixed portfolio'};
  const stageNames={resource:'Resources',separation:'Separation',metals:'Metal / master alloy',magnets:'Magnet production',qualification:'Qualification',consumption:'Application demand'};
  const mapStageFor={resource:'origin',separation:'processing',metals:'conversion',magnets:'manufacturing','nonree-inputs':'conversion',qualification:null,consumption:null};
  const params=new URLSearchParams(location.search);
  let defaults,config,simulation,comparison,maps,worldData,evidenceConfig,applicationData,selectedSectorId=params.get('sector')||'generic',selectedApplicationPlantId=params.get('application_plant')||'',pathId=params.get('path')||'',selectedPlace=params.get('place')||'',selectedStage=Object.entries(mapStageFor).find(([,s])=>s===params.get('stage'))?.[0]||'separation',selectedMonth=0,busy=false,dirty=false,requestNumber=0;
  const get=(obj,path)=>path.split('.').reduce((v,k)=>v?.[k],obj);
  const set=(obj,path,value)=>{const keys=path.split('.');let target=obj;for(const k of keys.slice(0,-1))target=target[k]??={};target[keys.at(-1)]=value;};
  const clone=obj=>JSON.parse(JSON.stringify(obj));
  const status=(text,error=false)=>{$('chain-status').textContent=text;$('chain-status').classList.toggle('error',error);};
  const selectField=(key,label,options)=>`<label class="cl-field"><span>${esc(label)}</span><select data-config="${key}">${options.map(([value,name])=>`<option value="${esc(value)}" ${String(get(config,key))===String(value)?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
  function numberField(key,label,{min=0,max=100,step=1,unit='',range=false}={}){const value=get(config,key);if(typeof value!=='number')return '';return `<label class="cl-field"><span>${esc(label)}</span>${range?`<output data-output="${key}">${fmt(value,step<1?2:0)} ${esc(unit)}</output>`:''}<input data-config="${key}" type="${range?'range':'number'}" value="${value}" min="${min}" max="${max}" step="${step}" aria-label="${esc(label)}${unit?' in '+esc(unit):''}"></label>`;}
  function renderControls(){
    const stages=[['resource','Resource extraction'],['separation','REE separation'],['metals','Metal / master alloy'],['magnets','Magnet manufacturing'],['qualification','Acceptance'],['nonree-inputs','Fe / B / minor inputs']];
    $('chain-controls').innerHTML=`<section class="cl-control-group"><h3>The disruption</h3>${selectField('shock_stage','Stage hit',stages)}${selectField('shock_region','Capacity region',[['China','China'],['Independent','Independent pool']])}${numberField('shock_retention','Capacity retained',{max:1,step:.05,unit:'fraction',range:true})}${numberField('shock_start_month','First shock month',{min:1,max:120})}${numberField('shock_duration_months','Shock duration',{max:60,unit:'months'})}${selectField('shock_element','Affected elements',[['all','All model elements'],['Nd','Nd · neodymium'],['Pr','Pr · praseodymium'],['Dy','Dy · dysprosium'],['Tb','Tb · terbium'],['Fe','Fe · iron'],['B','B · boron']])}<div id="chain-applicability-input"></div><p>Capacity loss is assumed. It is not a forecast of an export restriction or a specific plant outage.</p></section>
      <section class="cl-control-group"><h3>The service boundary</h3><label class="cl-field"><span>Application context</span><select id="chain-sector"><option value="generic">Generic assumed consumption</option>${(applicationData?.sectors||[]).map(s=>`<option value="${esc(s.id)}" ${s.id===selectedSectorId?'selected':''}>${esc(s.label)}</option>`).join('')}</select></label>${selectField('recipe_id','Composition example',[['n33u','Published N33U specimen'],['n52-patent','Published N52 patent example']])}<label class="cl-field"><span>Assumed application label</span><input data-config="application_label" type="text" maxlength="140" value="${esc(config.application_label)}"></label>${numberField('annual_demand_tonnes','Accepted magnet demand (t/year)',{min:0,max:100000,step:1,unit:'tonnes/year'})}${numberField('supply_reference_annual_tonnes','Fixed supply reference (t/year)',{min:1,max:100000,step:1,unit:'tonnes/year'})}${numberField('horizon_months','Simulation horizon',{min:6,max:120,unit:'months'})}${numberField('deadline_month','Delivery deadline',{min:1,max:120,unit:'month'})}<p>Demand does not rescale assumed supply capacity or initial stocks. An alloy example is not a guaranteed sector recipe, and no named customer is inferred.</p></section>
      <section class="cl-control-group"><h3>The response</h3>${numberField('budget','Common intervention budget',{max:1000,step:10,unit:'scenario credits',range:true})}${numberField('decision_month','Investment decision month',{min:1,max:120})}${selectField('policy','Inspect one policy',Object.entries(policyNames))}${selectField('initial_pipeline_mode','Initial pipeline',[['warm','Existing steady-state material'],['empty','Empty pipeline']])}<p>Initial inventory controls are referenced to the fixed supply anchor. An empty pipeline plus all stocks at zero is a cold start. Every funded comparison uses the same budget and horizon.</p></section>
      <details><summary>Inspect stage yields, lead times, finite stocks & project readiness</summary><p class="cl-small">All of these quantities are scenario assumptions. Physical stocks retain their own product or contained-element units.</p><div id="chain-advanced-fields" class="cl-stage-inputs"></div></details>`;
    renderAdvanced();renderInputApplicability();renderApplicationContext();
  }
  function renderAdvanced(){
    const groups=[];
    for(const [key,label] of [['stage_yields','Stage recovery / yield'],['stage_capacity_factors','Stage capacity multipliers'],['lead_months','Process lead times'],['inventory_months','Initial finite inventories'],['china_share','Assumed China capacity fractions'],['construction_months','Project construction'],['mix','Mixed budget allocation'],['cost_per_capacity_fraction','Assumed capacity costs']]){
      const values=config[key];if(!values||typeof values!=='object')continue;
      const fields=Object.entries(values).filter(([,v])=>typeof v==='number').map(([stage])=>numberField(`${key}.${stage}`,stageNames[stage]||policyNames[stage]||stage.replaceAll('_',' '),['stage_yields','china_share','mix'].includes(key)?{min:key==='stage_yields'?.01:0,max:1,step:.01,unit:key==='mix'?'budget fraction':'fraction'}:key==='stage_capacity_factors'?{max:5,step:.05,unit:'× base capacity'}:key==='cost_per_capacity_fraction'?{min:1,max:2000,step:1,unit:'credits / fraction'}:{min:key==='lead_months'?1:0,max:60,step:key==='inventory_months'?.25:1,unit:'months'})).join('');
      if(fields)groups.push(`<fieldset><legend>${label}</legend>${fields}</fieldset>`);
    }
    groups.push(`<fieldset><legend>Readiness & buffer procurement</legend>${numberField('capacity_headroom','Baseline capacity headroom',{max:2,step:.05,unit:'fraction'})}${numberField('ramp_months','Project ramp',{min:1,max:60,unit:'months'})}${numberField('project_qualification_months','New project qualification',{max:60,unit:'months'})}${numberField('inventory_purchase_lead_months','Paid stock procurement lead',{min:1,max:60,unit:'months'})}${numberField('inventory_cost_per_tonne','Qualified inventory cost',{min:.01,max:100,step:.01,unit:'credits / tonne'})}</fieldset>`);
    if(config.feedstock_assays)groups.push(advancedObject('feedstock_assays',config.feedstock_assays));
    $('chain-advanced-fields').innerHTML=groups.join('')+'<p class="cl-small">Each purchased-alloy assay must sum to 1. Mixed budget fractions must sum to 1. No normalization or impurity balance is silently added. Capacity multipliers and geographic fractions describe a representative regional network, not named map facilities.</p>';
  }
  function advancedObject(prefix,obj){return Object.entries(obj).map(([key,value])=>{if(typeof value==='number')return `<fieldset><legend>${esc(prefix.replaceAll('_',' '))}</legend>${numberField(`${prefix}.${key}`,key.replaceAll('_',' '),{max:/fraction|share|yield/.test(key)?1:120,step:/fraction|share|yield/.test(key)?.05:1})}</fieldset>`;if(value&&typeof value==='object'&&!Array.isArray(value)){const fields=Object.entries(value).filter(([,v])=>typeof v==='number').map(([k])=>numberField(`${prefix}.${key}.${k}`,k.replaceAll('_',' '),{max:prefix==='feedstock_assays'||/share|fraction|yield/.test(k)?1:120,step:prefix==='feedstock_assays'?.01:/share|fraction|yield/.test(k)?.05:1,unit:prefix==='feedstock_assays'?'mass fraction':''})).join('');return fields?`<fieldset><legend>${esc((policyNames[key]||key).replaceAll('_',' '))}</legend>${fields}</fieldset>`:'';}return '';}).join('');}
  function applicabilityNote(recipe,element){
    if(!recipe||!element||element==='all')return '';
    const composition=recipe.composition_wt_pct||{},amount=element==='NdPr'?(composition.Nd||0)+(composition.Pr||0):(composition[element]||0);
    if(amount>0)return '';
    const name=({Tb:'terbium',Dy:'dysprosium',Nd:'neodymium',Pr:'praseodymium',Fe:'iron',B:'boron',NdPr:'neodymium + praseodymium'})[element]||element;
    return `<div class="cl-reference-note" role="note" style="grid-column:1/-1"><strong>Specimen applicability · no tracked ${esc(element)}</strong><p>The selected example (${esc(recipe.label)}) has no tracked ${esc(name)} (${esc(element)}) in its modeled composition. A shock targeting ${esc(element)} therefore has no direct effect on its tracked material supply in this model. This does not establish the risk for ${esc(element)}-dependent grades or grain-boundary diffusion treatments.</p></div>`;
  }
  function renderInputApplicability(){const recipe=evidenceConfig?.recipes?.find(r=>r.id===config?.recipe_id);const note=$('chain-applicability-input');if(note)note.innerHTML=applicabilityNote(recipe,config?.shock_element);}
  const applicationSector=()=>applicationData?.sectors?.find(s=>s.id===selectedSectorId);
  const applicationPlant=(id=selectedApplicationPlantId)=>applicationData?.plants?.find(p=>p.id===id);
  function sectorSupportsNdFeB(s){return !s||s.model_compatibility==='ndfeb_context'||(!s.model_compatibility&&['ev_traction','robot_automation','pm_wind'].includes(s.id));}
  function contextSupportsNdFeB(s=applicationSector(),p=applicationPlant()){return sectorSupportsNdFeB(s)&&(!p?.model_compatibility||p.model_compatibility==='ndfeb_context')&&!/smco|samarium.?cobalt/i.test(`${p?.product||''} ${p?.plant_type||''}`);}
  function validateApplicationPlant(){const p=applicationPlant();if(!p||(selectedSectorId!=='generic'&&!(p.sector_ids||[]).includes(selectedSectorId)))selectedApplicationPlantId='';}
  function applicationMapLink(p,sectorId=selectedSectorId){const q=new URLSearchParams({layer:'applications',plant:p.id});if(sectorId!=='generic')q.set('sector',sectorId);return `grades.html?${q}#origins`;}
  function applicationPlantHTML(p,sectorId=selectedSectorId){return p?`<p><strong>Selected application place · contextual reference only</strong><br>${esc(p.name)} · ${esc(p.status_label||p.status||'See cited status')}<br>${esc(p.product||'Product not assigned')}<br>${esc(p.place||p.city||p.region||'Reported location')} · ${esc(p.country||'Country not assigned')}</p>${p.architecture_context?`<p>${esc(typeof p.architecture_context==='string'?p.architecture_context:p.architecture_context.statement||'')}</p>`:''}${p.model_boundary?`<p><strong>Selected place is outside the model</strong><br>${esc(p.model_boundary)}</p>`:''}<p class="cl-small">${esc(p.location_note||p.location_precision||'Reported place only; no surveyed factory coordinate is inferred.')} Source record: ${esc(p.id)}. It is not assigned the modeled customer demand, recipe, capacity or delivered allocation.</p><p><a href="${applicationMapLink(p,sectorId)}">Inspect this application map record ↗</a></p>`:'';}
  function renderApplicationContext(){
    const s=applicationSector(),p=applicationPlant(),note=$('chain-application-context'),eligible=contextSupportsNdFeB(s,p);note.hidden=!s&&!p;if(note.hidden){note.innerHTML='';return;}
    note.innerHTML=(s?`<strong>${esc(s.label)} · ${eligible?'application context, not a calibrated bill of materials':'outside the modeled NdFeB chemistry'}</strong><p>${esc(typeof s.technology_boundary==='string'?s.technology_boundary:s.technology_boundary?.statement||'Technology choice determines whether this application uses rare-earth permanent magnets.')} ${eligible?'Neither the N33U specimen nor the N52 patent example is asserted to fit this sector. Demand and acceptance timing remain editable assumptions; adjust qualification lead time and new-project qualification in the advanced controls.':'This sector is not assigned either NdFeB composition example. The figures below remain a separate generic NdFeB experiment; they do not simulate SmCo, superconducting magnets or an unspecified magnet chemistry.'} ${esc(s.model_boundary||'')}</p><p><a href="applications.html?sector=${encodeURIComponent(s.id)}">Read sourced requirements, alternatives, manufacturers & plants ↗</a></p>`:'<strong>Application place · context without a sector-specific assumption</strong>')+applicationPlantHTML(p);
  }
  function markDirty(){dirty=true;$('chain-revision').textContent='Controls changed. Run again to update every result.';status('Unsaved experiment changes. Existing figures still show the previous run.');}
  function lock(value){busy=value;for(const id of ['chain-run','chain-reset'])$(id).disabled=value;}
  async function run(){
    if(busy||!config||!$('chain-controls').reportValidity())return;const serial=++requestNumber,input=clone(config);input.map_context=contextSnapshot();lock(true);status('Running the canonical Python chain and equal-budget comparisons…');
    try{
      const [result,compared]=await Promise.all([RareEarthRuntime.chainSimulate(input),RareEarthRuntime.chainCompare(input)]);if(serial!==requestNumber)return;
      simulation=result;comparison=compared;config=clone(result.config||input);selectedMonth=Math.min(selectedMonth,result.monthly.length-1);dirty=false;
      renderResults();$('chain-results').hidden=false;$('chain-download').disabled=false;$('chain-revision').textContent=`Computed from saved assumptions · ${config.horizon_months} months · ${policyNames[config.policy]||config.policy}`;
      status(result.audit?.material_balance_pass&&result.audit?.nonnegative_stocks?'Run complete. Material balance and finite-stock checks passed.':'Run complete. Inspect the accounting audit before interpreting the figures.',!(result.audit?.material_balance_pass&&result.audit?.nonnegative_stocks));
    }catch(e){status(`The Python model could not complete: ${e.message}. No replacement results have been estimated in the browser.`,true);}finally{lock(false);}
  }
  function activeRun(){return simulation;}
  function renderResults(){
    const run=activeRun(),m=run.metrics,deadline=m.deadline||{};
    $('chain-kpis').innerHTML=`<div><span>Qualified delivery by deadline</span><strong>${fmt(deadline.delivered_usable_tonnes)} t</strong><small>Through month ${deadline.month} · assumed application acceptance</small></div><div><span>Unmet demand by deadline</span><strong>${fmt(deadline.unmet_qualified_tonnes)} t</strong><small>${fmt(deadline.demand_tonnes)} t cumulative demand</small></div><div><span>Full-horizon service</span><strong>${fmt(m.service_fraction*100)}%</strong><small>${fmt(m.delivered_usable_tonnes)} t delivered / ${fmt(m.demand_tonnes)} t demand</small></div><div><span>Backlog burden</span><strong>${fmt(m.backlog_tonne_months,0)}</strong><small>tonne-months · quantity × time waiting</small></div>`;
    $('chain-month').innerHTML=run.monthly.map((row,i)=>`<option value="${i}" ${i===selectedMonth?'selected':''}>Month ${row.month}</option>`).join('');
    const cf=run.counterfactual,unshocked=cf?.no_shock_metrics;
    const initial=run.initial_state,initialNote=initial?`<strong>Initial material · explicit finite ledger</strong><p>${fmt(initial.stock_total_tracked_elements_tonnes)} t tracked elements in initial working stocks + ${fmt(initial.pipeline_total_tracked_elements_tonnes)} t tracked elements already in transit. Pipeline mode: ${esc(initial.pipeline_mode||run.config.initial_pipeline_mode)}. Fixed supply reference: ${fmt(run.config.supply_reference_annual_tonnes)} t/year; demand is independently ${fmt(run.config.annual_demand_tonnes)} t/year. These totals are tracked-element mass, not ore or oxide-product tonnes.</p>`:'';
    $('chain-reference-note').innerHTML=initialNote+(unshocked?`<strong>Unshocked reference · same policy & initial state</strong><p>${fmt(unshocked.backlog_tonne_months,0)} tonne-months backlog without the shock. Shock increment: ${fmt(cf.shock_increment_backlog_tonne_months,0)} tonne-months; ${fmt(cf.deadline_shock_increment_unmet_qualified_tonnes)} t additional unmet demand by the deadline. ${esc(cf.basis||'')}</p>`:'<p>The unshocked counterfactual is unavailable in this runtime. Do not attribute all backlog to the shock.</p>');
    renderChain();renderServiceChart();renderComparison();renderFindings();renderMethods();
  }
  const icons={
    resource:'<path d="M6 56 34 10l22 35 12-17 26 28Z"/><path d="m25 26 9-16 12 19-12-4Z"/><path d="M13 59h64m-52-9 9-15 7 10"/><path d="M61 48h25v12H61zM72 39h12v9H72z"/><circle cx="66" cy="61" r="4"/><circle cx="82" cy="61" r="4"/>',
    separation:'<path d="M13 19h21v38H13zM40 12h22v45H40zM69 24h20v33H69zM23 19V7h28v5m0 0V5h28v19M7 59h87"/><path d="M14 36h19m8-10h20m9 17h18"/><circle cx="51" cy="40" r="7"/><path d="M51 33v14m-7-7h14"/>',
    metals:'<path d="M15 16h38l-7 30H23Z"/><path d="M12 12h44v6H12zM21 48h30v12H21zM54 25l16 13v8"/><ellipse cx="74" cy="53" rx="13" ry="13"/><path d="M61 53h26m-13-13v26M88 55h8v6H80"/><path d="m31 38 4-14 4 14" fill="#c5a46b"/>',
    magnets:'<path d="M18 6h60v9H18zM22 15v45m52-45v45M18 60h60v6H18zM36 15v13h24V15M34 29h28v10H34zM38 44h20v13H38z"/><path d="M46 16v10m4-10v10M81 47h12v13H81z"/>',
    qualification:'<path d="M17 57V15h50v42zM25 23h32v22H25zM68 53h21v10H68z"/><path d="m32 34 7 7 15-17M73 23l13 10-5 15H66l-4-15Z"/><path d="m68 34 5 5 8-9"/>',
    consumption:'<circle cx="48" cy="35" r="23"/><circle cx="48" cy="35" r="9"/><path d="M48 26V13m9 22h14M48 44v13M39 35H25M7 35h18m46 0h23M34 58v7h30v-7"/><path d="m34 18 8 11m22-10-9 11m9 23-10-11m-21 10 10-10"/>'
  };
  function throughputFor(row,stage){return row.throughput?.[stage];}
  function numberSummary(value,unit){if(typeof value==='number')return `${fmt(value)} ${unit}`;if(value&&typeof value==='object'){if(value.unit&&Number.isFinite(value.output_tonnes))return `${fmt(value.output_tonnes)} ${value.unit}`;return Object.entries(value).map(([k,v])=>typeof v==='number'?`${k}: ${fmt(v)} ${unit}`:v&&typeof v==='object'?`${k}: ${numberSummary(v,unit)}`:'').filter(Boolean).join(' · ');}return 'See stage accounts';}
  function feedstockGraphic(){const p=simulation.feedstock_plan,values=Object.entries(p.products_tonnes_per_tonne_alloy),colors=['#c5a46b','#b29d79','#bb785d','#8aab95','#607e69','#aaa4ce','#77a8b8','#b8b89b'];return `<div class="cl-feedstock"><p class="eyebrow">Ideal purchased basket / 100 kg charge</p><div class="cl-feedstock-bar" role="img" aria-label="Purchased alloy and pure metal mass fractions">${values.map(([name,v],i)=>`<span style="width:${v*100}%;background:${colors[i%colors.length]}" title="${esc(name)}: ${fmt(v*100,2)} kg"></span>`).join('')}</div><div class="cl-feedstock-key">${values.map(([name,v],i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${esc(name)} ${fmt(v*100,2)} kg</span>`).join('')}</div><p class="cl-small">DyFe + FeB already contribute ${fmt(Object.values(p.carrier_fe_tonnes_per_tonne_alloy).reduce((a,b)=>a+b,0)*100,2)} kg carrier Fe. Pure-Fe charge subtracts that contribution. Ideal assay accounting; process losses are separate.</p></div>`;}
  function renderChain(){
    const row=simulation.monthly[selectedMonth],bottle=row.bottleneck_stage;
    $('chain-flow-note').textContent=`Month ${row.month} · arrows are assumed process links, not observed shipments. REE contained-element tonnes and purchased-product tonnes remain separate.`;
    $('chain-graph').innerHTML=Object.entries(stageNames).map(([id,name],i)=>{const account=throughputFor(row,id),value=id==='consumption'?row.demand_tonnes:account?.output_tonnes,capacity=row.capacity?.[id]?.output_tonnes,unit=id==='consumption'?'magnet tonnes demanded':account?.unit||'stage-specific tonnes',utilization=capacity>0?Math.min(100,100*(value||0)/capacity):null;return `<button type="button" class="cl-stage ${id===selectedStage?'selected':''} ${bottle===id?'bottleneck':''}" data-chain-stage="${id}" aria-pressed="${id===selectedStage}"><span class="cl-stage-index">0${i+1} / ${id==='consumption'?'DEMAND':'ASSUMED STAGE'}</span><svg viewBox="0 0 100 72" aria-hidden="true">${icons[id]}</svg><h3>${name}</h3><span class="cl-stage-output">${Number.isFinite(value)?fmt(value)+' t':'Inspect'}</span><span class="cl-stage-meta">${esc(unit)}${utilization!==null?`<br>${fmt(utilization,0)}% of this stage’s capacity`:''}</span>${utilization!==null?`<div class="cl-stage-bar"><i style="width:${utilization}%"></i></div>`:''}</button>`;}).join('');
    $('chain-nonree').classList.toggle('selected',selectedStage==='nonree-inputs');renderStageDetail();renderReadiness();renderEvidence();
  }
  function renderReadiness(){const row=simulation.monthly[selectedMonth];$('chain-readiness').innerHTML=Object.entries(row.project_readiness||{}).map(([policy,p])=>`<article><span>${esc(policyNames[policy]||policy)}</span><strong>${esc(p.state.replaceAll('-',' '))}</strong><div class="cl-ready-track" aria-hidden="true">${Array.from({length:5},(_,i)=>`<i class="${p.budget_credits>0&&(policy==='finished-inventory'?p.state==='arrived':(p.ramp_fraction||0)>(i/5))?'ready':''}"></i>`).join('')}</div><p>${policy==='finished-inventory'?`One ${fmt(p.finite_order_tonnes)} t paid external stock order<br>Order month ${p.order_month} · arrival month ${p.arrival_month}<br>Assumed purchased availability; not mine production.`:`Commission month ${p.commission_month}<br>Qualification complete ${p.qualification_complete_month}<br>Full capacity month ${p.full_capacity_month}`}<br>${fmt(p.budget_credits)} credits allocated</p></article>`).join('');}
  function renderStageDetail(){
    const row=simulation.monthly[selectedMonth],id=selectedStage,stock=row.stocks?.[{resource:'raw',separation:'separated',metals:'feedstocks',magnets:'unqualified',qualification:'qualified','nonree-inputs':'nonree'}[id]],throughput=throughputFor(row,id),capacity=row.capacity?.[id],same=stageContextNodes(id);
    const stockUnit=['resource','separation','nonree-inputs'].includes(id)?'t contained element':id==='metals'?'t purchased product':'t magnet';
    $('chain-stage-detail').innerHTML=`<div><p class="eyebrow">${id==='consumption'?'Generic service boundary':'Assumed scenario account'}</p><h3>${stageNames[id]||'Fe / B / minor inputs'}</h3><p>${id==='consumption'?`${esc(simulation.config.application_label)}: ${fmt(row.demand_tonnes)} t demand; ${fmt(row.delivered_usable_tonnes)} t usable magnets delivered this month. ${fmt(row.backlog_tonnes)} t remain waiting.`:`Throughput: ${esc(numberSummary(throughput,stockUnit))}.<br>Stock: ${esc(numberSummary(stock,stockUnit))}.<br>Capacity: ${esc(numberSummary(capacity,'stage tonnes / month'))}.`}</p><p class="cl-small">${row.bottleneck_stage===id?'This month’s model bottleneck. ':''}These are two assumed regional pools; a map pin never receives a regional capacity share. The highlighted stage is not a diagnosis of a mapped operator.</p></div><div><p class="eyebrow">Selected hypothetical reference anchors · ${same.length}</p><p>${same.length?same.map(n=>`<a href="#chain-evidence" data-context-place="${esc(n.id)}">${esc(n.name)} · ${esc(n.status_label||n.status)}<br><small>Source node: ${esc(n.id)} · capacity / specimen assignment unknown</small></a>`).join('<br>'):'No evidenced site is assigned to this scenario stage. Its location, counterparty or specimen acceptance remains a gap.'}</p><p class="cl-small">${path()&&same.some(n=>!pathNodes().some(p=>p.id===n.id))?'Reference anchors outside the selected fragment fill no proven route; their connections stay assumed. ':''}Fe, B and minor inputs bypass REE separation; master alloys contribute their carrier iron. Every model process edge is assumed unless separately identified as a source relationship.</p></div>`;
    if(id==='metals'||id==='nonree-inputs')$('chain-stage-detail').firstElementChild.insertAdjacentHTML('beforeend',feedstockGraphic());
    if(id==='consumption'){const sectorId=simulation.map_context?.application_sector_id||'generic',sector=applicationData?.sectors?.find(s=>s.id===sectorId),p=applicationPlant(simulation.map_context?.application_plant_id||null);$('chain-stage-detail').lastElementChild.insertAdjacentHTML('beforeend',(sector?`<p><a href="applications.html?sector=${encodeURIComponent(sector.id)}">${esc(sector.label)}: sourced requirements, alternative designs & physical manufacturer plants ↗</a></p><p class="cl-small">${contextSupportsNdFeB(sector,p)?'These manufacturing records are context for an application. None is asserted to be the simulated customer, to accept either composition example, or to consume this modeled allocation.':'The selected application or place has a chemistry outside this model. These figures describe a separate generic NdFeB experiment, not delivery to this documented chain.'}</p>`:'')+applicationPlantHTML(p,sectorId));}
  }
  function renderServiceChart(){
    const svg=d3.select('#chain-service-chart');svg.selectAll('*').remove();const rows=simulation.monthly,w=700,h=310,margin={left:62,right:17,top:22,bottom:45};let demand=0,delivery=0;const points=rows.map(r=>({month:r.month,demand:demand+=r.demand_tonnes,delivery:delivery+=r.delivered_usable_tonnes,backlog:r.backlog_tonnes}));
    const x=d3.scaleLinear().domain([0,rows.at(-1).month]).range([margin.left,w-margin.right]),y=d3.scaleLinear().domain([0,d3.max(points,p=>Math.max(p.demand,p.delivery))||1]).nice().range([h-margin.bottom,margin.top]);
    svg.append('g').attr('class','cl-grid').attr('transform',`translate(${margin.left},0)`).call(d3.axisLeft(y).ticks(4).tickSize(-(w-margin.left-margin.right)).tickFormat('')).call(g=>g.select('.domain').remove());
    const start=Number(simulation.config.shock_start_month),end=start+Number(simulation.config.shock_duration_months);svg.append('rect').attr('x',x(start)).attr('y',margin.top).attr('width',Math.max(0,x(Math.min(rows.at(-1).month,end))-x(start))).attr('height',h-margin.top-margin.bottom).attr('fill','#bb785d18');
    for(const [key,color,dash] of [['demand','#c5a46b','6 5'],['delivery','#8aab95',null]])svg.append('path').datum([{month:0,demand:0,delivery:0},...points]).attr('fill','none').attr('stroke',color).attr('stroke-width',2.6).attr('stroke-dasharray',dash).attr('d',d3.line().x(p=>x(p.month)).y(p=>y(p[key])));
    svg.append('line').attr('x1',x(simulation.config.deadline_month)).attr('x2',x(simulation.config.deadline_month)).attr('y1',margin.top).attr('y2',h-margin.bottom).attr('stroke','#aaa4ce').attr('stroke-dasharray','3 4');
    svg.append('g').attr('transform',`translate(0,${h-margin.bottom})`).call(d3.axisBottom(x).ticks(6));svg.append('g').attr('transform',`translate(${margin.left},0)`).call(d3.axisLeft(y).ticks(4));svg.append('text').attr('x',margin.left).attr('y',11).text('Cumulative magnet tonnes');svg.append('text').attr('x',w-margin.right).attr('y',h-6).attr('text-anchor','end').text('Month');
    $('chain-service-key').innerHTML='<span class="dashed" style="--swatch:#c5a46b">Demand</span><span style="--swatch:#8aab95">Qualified delivery</span><span class="dashed" style="--swatch:#aaa4ce">Deadline</span><span style="--swatch:#bb785d">Shock window</span>';
  }
  function renderComparison(){
    const rows=comparison.comparison,svg=d3.select('#chain-compare-chart');svg.selectAll('*').remove();const w=700,h=310,m={left:174,right:65,top:20,bottom:38},x=d3.scaleLinear().domain([0,d3.max(rows,r=>r.deadline?.unmet_qualified_tonnes)||1]).nice().range([m.left,w-m.right]),y=d3.scaleBand().domain(rows.map(r=>r.policy)).range([m.top,h-m.bottom]).padding(.32);
    svg.selectAll('.delivered').data(rows).join('rect').attr('x',m.left).attr('y',r=>y(r.policy)).attr('height',y.bandwidth()).attr('width',r=>Math.max(0,x(r.deadline?.unmet_qualified_tonnes||0)-m.left)).attr('fill',r=>r.policy===simulation.config.policy?'#c5a46b':r.policy==='none'?'#788779':'#8aab95');
    svg.selectAll('.value').data(rows).join('text').attr('x',r=>x(r.deadline?.unmet_qualified_tonnes||0)+7).attr('y',r=>y(r.policy)+y.bandwidth()/2+4).text(r=>`${fmt(r.deadline?.unmet_qualified_tonnes)} t`);
    svg.append('g').attr('transform',`translate(0,${h-m.bottom})`).call(d3.axisBottom(x).ticks(4));svg.append('g').attr('transform',`translate(${m.left-10},0)`).call(d3.axisLeft(y).tickSize(0).tickFormat(p=>policyNames[p]||p)).call(g=>g.select('.domain').remove());svg.append('text').attr('x',w-m.right).attr('y',h-5).attr('text-anchor','end').text(`Unmet qualified tonnes by month ${simulation.config.deadline_month}`);
    $('chain-compare-note').textContent='Shorter bars mean less unmet demand at the common deadline. Backlog avoided in the cards measures the full horizon. Five candidate strategies are compared: four single interventions and one chosen mix. This is not a portfolio optimizer or a dollar ranking.';
    $('chain-comparison').innerHTML=rows.filter(r=>r.policy!=='none').map(r=>`<article class="${r.policy===simulation.config.policy?'selected':''}"><h3>${policyNames[r.policy]||esc(r.policy)}</h3><strong>${fmt(r.deadline?.delivered_usable_tonnes)} t</strong><p>Qualified delivery by deadline<br>${fmt(r.avoided_backlog_tonne_months,0)} tonne-months of backlog avoided over horizon<br>${fmt(r.policy_budget_spent)} credits spent</p><button type="button" data-inspect-policy="${esc(r.policy)}">Inspect this run</button></article>`).join('');
  }
  function renderFindings(){const m=simulation.metrics;const ranked=[...comparison.comparison].filter(r=>r.policy!=='none').sort((a,b)=>(b.deadline?.delivered_usable_tonnes||0)-(a.deadline?.delivered_usable_tonnes||0)),best=ranked[0],tied=best?ranked.filter(r=>Math.abs((r.deadline?.delivered_usable_tonnes||0)-(best.deadline?.delivered_usable_tonnes||0))<1e-6):[],names=tied.map(r=>policyNames[r.policy]||r.policy),title=tied.length>1?'These policies tie at the delivery deadline.':best?`${policyNames[best.policy]||best.policy} ${best.policy==='finished-inventory'?'deliver':'delivers'} most by this deadline.`:'Inspect the scenario results.';$('chain-findings').innerHTML=`${applicabilityNote(simulation.recipe,simulation.config.shock_element)}<div><p class="eyebrow">A conditional finding</p><h3>${esc(title)}</h3><p>Among these five compared policies, ${tied.length>1?`${esc(names.join(', '))} each deliver ${fmt(best.deadline.delivered_usable_tonnes)} t by month ${simulation.config.deadline_month}. There is no distinguishable winner on this metric. `:best?`${fmt(best.deadline.delivered_usable_tonnes)} t of qualified delivery by month ${simulation.config.deadline_month}, under these assumed capacity, project-cost and readiness inputs. `:''}Longer horizons or different bottlenecks can change the comparison. This is an experiment result, not a recommendation for a real supplier or a national cost estimate.</p></div><div><p class="eyebrow">What to inspect next</p><p>Most frequent limiting state: ${esc(stageNames[m.bottleneck_stage]||({'pipeline-delay':'Material still in process / delivery lag'}[m.bottleneck_stage])||'No shortage observed')}.<br>Recovery: ${esc(m.recovery_month?`month ${m.recovery_month}`:m.recovery_status)}.<br>This diagnostic counts observed limiting states; it does not identify the causal origin of the shock. The unshocked reference separates shock effects from initial-state effects. Mining diversity changes geography without adding total resource capacity.</p></div>`;}
  function renderMethods(){const a=simulation.audit,recipe=simulation.recipe;$('chain-methods').innerHTML=`<p>Model scope: monthly physical availability for a generic assumed application, with separate elemental accounts and purchased-product forms. No named customer, transport itinerary or mapped operator’s capacity is inferred.</p><p>Composition source: <a href="${esc(recipe.source_url)}" target="_blank" rel="noopener">${esc(recipe.label)}</a> · ${esc(recipe.source_locator)} · ${esc(recipe.source_status)}.</p><p>Accounting audit: maximum absolute element-balance residual ${fmt(a.max_abs_balance_residual_tonnes,8)} t; material balance ${a.material_balance_pass?'passed':'FAILED'}; nonnegative stocks ${a.nonnegative_stocks?'passed':'FAILED'}.</p><p>Initial state: ${esc(simulation.initial_state?.basis||'Finite initial stocks and pipeline are part of the tracked initial element ledger.')} Paid qualified inventory is a separate finite external purchase, recorded in transit before its assumed arrival; it is not modeled mine production or proven supplier availability.</p><p>Budget credits are illustrative cost assumptions, not dollars. All comparisons use the same budget and deadline; time to construct, ramp and qualify is part of the scenario. Purchases cannot arrive before their modeled readiness.</p><p>Published composition examples establish their reported material content only. They do not predict the grade of a newly made part. NdPr, DyFe and FeB use purchased-product assays and carrier iron; Tb is terbium, not boron.</p><p>Evidence map pins establish approximate geography and cited product/status context. The scenario topology is separately assumed. A known source relationship does not calibrate its mass, eligible demand, available allocation or current qualification.</p>${(comparison.limitations||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<p><a href="data/supply-chain.json">Download the model assumptions and evidence boundary</a> · <a href="grades.html#composition">Inspect purchased-alloy accounting</a> · <a href="investment.html#investment-study">Read the investment framework</a></p>`;}
  const allPlaces=()=>maps?[...(maps.nodes||[]),...(maps.route_nodes||[]),...(maps.unlocated_nodes||[])]:[];
  const place=id=>allPlaces().find(n=>n.id===id);
  const path=()=>maps?.map_paths.find(p=>p.id===pathId);
  const pathNodes=()=>{const p=path();return p?[...new Set(p.steps.flatMap(s=>typeof s==='string'?[s]:s.unlocated_id?[s.unlocated_id]:[]))].map(place).filter(Boolean):[];};
  const nodeStages=n=>n.stage_tags||[n.stage||'entry'];
  function stageContextNodes(id){if(!maps||id==='consumption')return [];const candidates=[...new Map([...pathNodes(),...(!pathId&&params.get('place')&&place(params.get('place'))?[place(params.get('place'))]:[])].map(n=>[n.id,n])).values()],matching=id==='qualification'?[]:candidates.filter(n=>nodeStages(n).includes(mapStageFor[id])&&(id!=='nonree-inputs'||(n.materials||[]).some(m=>['Fe','B'].includes(m))));if(matching.length)return matching;const refs=evidenceConfig?.stage_context?.[id]?.map_node_refs||[];return refs.map(place).filter(Boolean);}
  function contextSnapshot(){const p=path(),stageRefs=Object.fromEntries([...Object.keys(stageNames),'nonree-inputs'].map(id=>[id,stageContextNodes(id).map(n=>n.id)]));return {network_scope:'Representative China/Independent regional pools. Named reference anchors do not receive regional capacity, yield, inventory or specimen allocation.',application_sector_id:selectedSectorId,application_model_compatibility:applicationPlant()?.model_compatibility||applicationSector()?.model_compatibility||(contextSupportsNdFeB()?'ndfeb_context':'chemistry_unspecified'),application_plant_id:selectedApplicationPlantId||null,application_plant_source_ids:applicationPlant()?.source_ids||[],application_source_file:'data/application-supply.json',application_source_ids:applicationData?.sectors?.find(s=>s.id===selectedSectorId)?.source_ids||[],application_boundary:contextSupportsNdFeB()?'Sector and selected place are context only; neither source composition is asserted suitable, and demand / acceptance timing are assumed.':'Application chemistry is outside the model; results describe a separate generic NdFeB experiment, with no sector or customer allocation.',path_id:pathId||null,selected_place_id:selectedPlace||null,ingredient_filter:params.get('ingredient')||null,source_date:maps?.verified_on||null,source_file:'data/mine-routes.json',stage_refs:stageRefs,evidence_edge_refs:p?.route_ids||[],evidence_source_ids:[...new Set([...Object.values(stageRefs).flat().flatMap(id=>place(id)?.sources||[]),...maps?.routes.filter(r=>(p?.route_ids||[]).includes(r.id)).flatMap(r=>r.sources||[])||[]])],assumed_links:[['resource','separation'],['separation','metals'],['nonree-inputs','metals'],['metals','magnets'],['magnets','qualification'],['qualification','consumption']].map(([from,to])=>({from,to,status:'Assumed process link; not specimen provenance or verified physical delivery'})),gaps:[...(p?.steps||[]).filter(s=>typeof s!=='string').map(s=>({label:s.label,note:s.note||'',unlocated_id:s.unlocated_id||null})),...Object.entries(stageRefs).filter(([,refs])=>!refs.length).map(([stage])=>({stage,label:'No specimen-specific site or acceptance established'}))]};}
  function mapLink(node=null){const p=new URLSearchParams();if(pathId)p.set('path',pathId);if(node)p.set('place',node.id);if(['NdPr','Dy','Tb','Fe','B'].includes(params.get('ingredient')))p.set('ingredient',params.get('ingredient'));return `grades.html${p.size?'?'+p:''}#origins`;}
  function sourceLinks(ids){return [...new Set(ids||[])].map(id=>{const s=maps.sources.find(x=>x.id===id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}${s.publication_date||s.date?' · '+esc(s.publication_date||s.date):''} ↗</a>`:'';}).join('');}
  function showPlace(id){const n=place(id);if(!n)return;selectedPlace=id;const relations=maps.routes.filter(r=>r.source===id||r.target===id);$('chain-map-detail').innerHTML=`<p class="eyebrow">Documented map context</p><h3>${esc(n.name)}</h3><p class="cl-evidence-status">${esc(n.status_label||n.status)}</p><p>${esc(n.material_form||n.product||n.summary||'Product not disclosed')}</p><p>${esc(n.operator||'Operator not assigned')}<br>${esc(n.country||'Unlocated')}${n.region?' · '+esc(n.region):''}</p><p>${esc(n.location?.accuracy?`${n.location.accuracy} · ${n.location.method}`:n.location_note||'Location not mapped')}</p>${(n.caveats||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<p>Context for the selected scenario stage, not a measured allocation, inventory, yield or delivery assumption.</p><a href="${mapLink(n)}">Inspect this original map record ↗</a><details><summary>Primary evidence</summary>${sourceLinks(n.sources)}</details>${relations.length?`<details><summary>Related source relationships (${relations.length})</summary>${relations.map(r=>`<p>${esc(r.status_label||r.status)} · ${esc(r.summary||r.product||'')}</p>`).join('')}</details>`:''}`;d3.selectAll('#chain-context-map .cl-map-place').select('circle').attr('stroke',d=>d.id===id?'#e1c393':'#101614').attr('stroke-width',d=>d.id===id?3:1.5);}
  function renderEvidence(){
    if(!maps)return;const p=path(),nodes=[...new Map([...pathNodes(),...stageContextNodes(selectedStage)].map(n=>[n.id,n])).values()],mapped=nodes.filter(n=>Number.isFinite(n.lon)&&Number.isFinite(n.lat)),ids=new Set(mapped.map(n=>n.id)),stageIds=new Set(stageContextNodes(selectedStage).map(n=>n.id)),relations=maps.routes.filter(r=>p?.route_ids?.includes(r.id)&&r.draw_on_map!==false&&ids.has(r.source)&&ids.has(r.target));
    $('chain-open-map').href=mapLink();$('chain-map-note').textContent=`${mapped.length} approximate geographic reference${mapped.length===1?'':'s'} · ${relations.length} drawable source relationship${relations.length===1?'':'s'}. Equal-width lines do not establish tonnes. Scenario process arrows appear above, not as invented geographic routes.`;
    const card=n=>`<article><span>${stageIds.has(n.id)?'SELECTED STAGE ANCHOR':'SOURCE RECORD'}</span><button type="button" data-context-place="${esc(n.id)}">${esc(n.name)}</button><p>${esc(n.status_label||n.status)}</p><p>${esc(n.material_form||n.product||'')}</p><p>Node: ${esc(n.id)}</p></article>`;
    $('chain-evidence-path').innerHTML=(p?p.steps.map(s=>{const n=typeof s==='string'?place(s):s.unlocated_id?place(s.unlocated_id):null;return n?card(n):`<article class="gap"><span>EVIDENCE GAP</span><p>${esc(typeof s==='string'?s:s.label)}</p><p>${esc(typeof s==='object'?s.note||'':'')}</p></article>`;}).join('')+`<article class="gap"><span>BOUNDARY NOTE</span><p>${esc(p.note||'')}</p><p>${esc(p.us_connection||'')} The assumed model is not a reconstruction of this fragment.</p></article>`:'<article class="gap"><span>REPRESENTATIVE REGIONAL NETWORK</span><p>The quantitative chain uses assumed China/Independent regional pools. Named anchors are selected source context, not calibrated physical facilities.</p></article>')+stageContextNodes(selectedStage).filter(n=>!pathNodes().some(p=>p.id===n.id)).map(card).join('')+`<article class="gap"><span>ASSUMED SCENARIO EDGE</span><p>${esc(selectedStage==='nonree-inputs'?'Fe / B / minor elements → purchased feedstocks':selectedStage==='resource'?'Resources → separation':selectedStage==='separation'?'Separation → metal / master alloy':selectedStage==='metals'?'REE metals + Fe/B/minor inputs → magnet production':selectedStage==='magnets'?'Magnet production → acceptance':selectedStage==='qualification'?'Acceptance → generic application':'Generic application consumption')}</p><p>No source establishes this full specimen-specific delivery edge. Capacity and acceptance remain scenario inputs.</p></article>`;
    const svg=d3.select('#chain-context-map');svg.selectAll('*').remove();const projection=d3.geoNaturalEarth1().fitExtent([[20,20],[940,425]],{type:'Sphere'}),geo=d3.geoPath(projection);
    if(worldData){svg.append('path').datum(d3.geoGraticule10()).attr('d',geo).attr('fill','none').attr('stroke','#8aab9515');svg.selectAll('.cl-country').data(topojson.feature(worldData,worldData.objects.countries).features).join('path').attr('d',geo).attr('fill','#26362b').attr('stroke','#8aab9525').attr('stroke-width',.7);}
    svg.selectAll('.cl-map-route').data(relations).join('path').attr('d',r=>geo({type:'LineString',coordinates:[[place(r.source).lon,place(r.source).lat],[place(r.target).lon,place(r.target).lat]]})).attr('fill','none').attr('stroke',r=>stageIds.has(r.source)||stageIds.has(r.target)?'#e1c393':'#8aab95').attr('stroke-width',r=>stageIds.has(r.source)||stageIds.has(r.target)?3:1.5).attr('stroke-dasharray',r=>r.evidence_class==='reported'||r.physical_flow?'':'6 5').append('title').text(r=>`${r.id} · ${r.status_label||r.status}: ${r.summary||''}`);
    const group=svg.selectAll('.cl-map-place').data(mapped).join('g').attr('class','cl-map-place').attr('transform',n=>`translate(${projection([n.lon,n.lat])})`).attr('tabindex',0).attr('role','button').attr('aria-label',n=>`${n.name}: ${n.status_label||n.status}`).on('click',(_,n)=>showPlace(n.id)).on('keydown',(e,n)=>{if(['Enter',' '].includes(e.key)){e.preventDefault();showPlace(n.id);}});
    group.append('circle').attr('r',n=>stageIds.has(n.id)?7:5).attr('fill',n=>stageIds.has(n.id)?'#c5a46b':'#8aab95');group.append('title').text(n=>`${n.id} · ${n.name}: ${n.material_form||n.product||''}`);
    if(!nodes.some(n=>n.id===selectedPlace))selectedPlace=nodes.find(n=>stageIds.has(n.id))?.id||nodes[0]?.id;
    if(selectedPlace)showPlace(selectedPlace);else $('chain-map-detail').innerHTML='<p>Select a source-backed path. Anonymous customers and unlocated conversion gaps are not assigned map coordinates.</p>';
  }
  function download(content,filename,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const csvValue=v=>`"${String(v??'').replaceAll('"','""')}"`;
  const csv=(rows,keys)=>[keys.map(csvValue).join(','),...rows.map(r=>keys.map(k=>csvValue(typeof get(r,k)==='object'?JSON.stringify(get(r,k)):get(r,k))).join(','))].join('\n')+'\n';
  function addDownloadButtons(){for(const [id,label]of[['chain-monthly-csv','Monthly CSV'],['chain-comparison-csv','Comparison CSV']]){const b=document.createElement('button');b.id=id;b.type='button';b.textContent=label;b.disabled=true;$('chain-download').after(b);}const enable=()=>{for(const id of ['chain-monthly-csv','chain-comparison-csv'])$(id).disabled=!simulation;};new MutationObserver(enable).observe($('chain-download'),{attributes:true,attributeFilter:['disabled']});$('chain-monthly-csv').onclick=()=>download(csv(simulation.monthly,['month','demand_tonnes','delivered_usable_tonnes','backlog_tonnes','bottleneck_stage','stocks','pipeline','throughput','capacity','project_readiness','balance_residual_elements_tonnes']),'rare-earth-chain-monthly.csv','text/csv;charset=utf-8');$('chain-comparison-csv').onclick=()=>download(csv(comparison.comparison,['policy','policy_budget_spent','delivered_usable_tonnes','unmet_qualified_tonnes','backlog_tonne_months','service_fraction','deadline.month','deadline.delivered_usable_tonnes','deadline.unmet_qualified_tonnes','avoided_backlog_tonne_months','recovery_month','recovery_status']),'rare-earth-chain-comparison.csv','text/csv;charset=utf-8');}
  async function init(){
    addDownloadButtons();$('chain-controls').oninput=e=>{const key=e.target.dataset.config;if(!key)return;const value=e.target.type==='range'||e.target.type==='number'?Number(e.target.value):e.target.value;set(config,key,value);const out=document.querySelector(`[data-output="${key}"]`);if(out)out.textContent=`${fmt(value,2)} ${key==='budget'?'scenario credits':'fraction'}`;renderInputApplicability();markDirty();};$('chain-controls').onchange=e=>{if(e.target.id!=='chain-sector')return;selectedSectorId=e.target.value;validateApplicationPlant();const sector=applicationSector();config.application_label=contextSupportsNdFeB(sector)?sector?.application_label||sector?.scenario?.label||(sector?`Assumed ${sector.label} magnet demand`:defaults.application_label):defaults.application_label;renderControls();markDirty();};$('chain-controls').onsubmit=e=>{e.preventDefault();run();};$('chain-run').onclick=run;$('chain-reset').onclick=()=>{config=clone(defaults);selectedSectorId='generic';selectedApplicationPlantId='';renderControls();markDirty();};$('chain-month').onchange=e=>{selectedMonth=Number(e.target.value);renderChain();};
    $('chain-graph').onclick=e=>{const b=e.target.closest('[data-chain-stage]');if(b){selectedStage=b.dataset.chainStage;renderChain();}};
    $('chain-nonree').onclick=()=>{selectedStage='nonree-inputs';renderChain();};
    document.addEventListener('click',e=>{const n=e.target.closest('[data-context-place]');if(n)showPlace(n.dataset.contextPlace);const p=e.target.closest('[data-inspect-policy]');if(p&&comparison.runs?.[p.dataset.inspectPolicy]){simulation=comparison.runs[p.dataset.inspectPolicy];config=clone(simulation.config);selectedSectorId=simulation.map_context?.application_sector_id||'generic';selectedApplicationPlantId=simulation.map_context?.application_plant_id||'';validateApplicationPlant();selectedMonth=Math.min(selectedMonth,simulation.monthly.length-1);renderControls();renderResults();dirty=false;$('chain-revision').textContent=`Inspecting ${policyNames[config.policy]} from the same comparison.`;}});
    $('chain-map-path').onchange=e=>{pathId=e.target.value;renderEvidence();if(simulation)renderStageDetail();};$('chain-download').onclick=()=>download(JSON.stringify({saved_at:new Date().toISOString(),boundary:'Illustrative scenario; evidence pins are context, not calibrated shipments.',current_view_map_context:contextSnapshot(),selected_stage:selectedStage,simulation,comparison},null,2)+'\n','rare-earth-chain-experiment.json','application/json');
    const evidenceTasks=await Promise.allSettled([fetch('data/mine-routes.json').then(r=>{if(!r.ok)throw Error('map evidence');return r.json();}),fetch('assets/world-countries.json').then(r=>{if(!r.ok)throw Error('geography');return r.json();}),fetch('data/supply-chain.json').then(r=>{if(!r.ok)throw Error('model scope');return r.json();}),fetch('data/application-supply.json').then(r=>{if(!r.ok)throw Error('application evidence');return r.json();})]);
    if(evidenceTasks[2].status==='fulfilled')evidenceConfig=evidenceTasks[2].value;
    if(evidenceTasks[3].status==='fulfilled')applicationData=evidenceTasks[3].value;if(!applicationData?.sectors?.some(s=>s.id===selectedSectorId))selectedSectorId='generic';validateApplicationPlant();if(selectedApplicationPlantId&&!params.has('stage'))selectedStage='consumption';
    if(evidenceTasks[0].status==='fulfilled'){maps=evidenceTasks[0].value;worldData=evidenceTasks[1].status==='fulfilled'?evidenceTasks[1].value:null;if(!params.has('stage')&&place(selectedPlace))selectedStage=Object.entries(mapStageFor).find(([,stage])=>stage===place(selectedPlace).stage)?.[0]||'resource';if(!maps.map_paths.some(p=>p.id===pathId))pathId='';$('chain-map-path').innerHTML='<option value="">Choose an evidence fragment</option>'+maps.map_paths.map(p=>`<option value="${esc(p.id)}" ${p.id===pathId?'selected':''}>${esc(p.title)}</option>`).join('');renderEvidence();}else{$('chain-map-note').textContent='Map evidence could not load; no context links have been invented.';}
    try{defaults=await RareEarthRuntime.chainDefaults();config=clone(defaults);const sector=applicationData?.sectors?.find(s=>s.id===selectedSectorId);if(sector&&contextSupportsNdFeB(sector))config.application_label=sector.application_label||sector.scenario?.label||`Assumed ${sector.label} magnet demand`;renderControls();lock(false);await run();}catch(e){status(`The shared Python research runtime could not load: ${e.message}. Reload to retry.`,true);}
  }
  init();
})();
